------------------
Build instructions
------------------

Required tools:
* Cmake 
* c/c++ compiler (gcc)
* opencv > 3.1.0

-----------------
Linux compilation
-----------------
cmake .
make
./FindWill <your src image path> <your template image path>
