------------------
Build instructions
------------------

Required tools:
* Cmake 
* c/c++ compiler (gcc)
* opencv > 3.1.0

-----------------
Linux compilation
-----------------
cmake .
make



-----------------
How to run
-----------------
./Pick <your src image path> <the result image path>
left click to extract and save the superpixel around the pixel location
press any key to exit


