------------------
Build instructions
------------------

Required tools:
* Cmake 
* c/c++ compiler (gcc)
* opencv > 3.1.0

-----------------
Linux compilation
-----------------
cmake .
make



-----------------
How to run
-----------------
./Registration <source image path> <temlate image path> <canny image of dst> <canny image of template> <the cols location> <text file name> <result image path>

Tips:
This Registration application must run after you've picked the temlate images.
The source image here is different from the one in the pick application. They are just captured based on same location and different height.
The talk about compute the distance between these two points is beyond this scope.

